"""Focused checks for the solver-neutral ordered-boundary inverse seam.

These tests deliberately use exact Mie-series scattered data rather than data
generated by either numerical solver.  The inverse test is low dimensional on
purpose: parameter-level finite differences are an auditable common baseline,
not a scalable substitute for a neural-network adjoint.
"""

from __future__ import annotations

import math
from types import SimpleNamespace

import numpy as np
import pytest

torch = pytest.importorskip("torch")

import config.circle_config as cfg
from gpr_bem_ref import Material, penetrable_cylinder_frequency_response
from sdf_inverse.forward import (
    MaterialSpec,
    PairedForwardProblem,
    predict_paired_response,
)
from sdf_inverse.geometry import (
    OrderedSDFGeometryConfig,
    build_ordered_sdf_geometry,
    ordered_curve_to_mod_boundary,
)
from sdf_inverse.models import (
    CircleSDF2D,
    EllipseLevelSet2D,
    RadialRandomFeatureImplicit2D,
    TorchParameterController,
    build_circle_parameter_controller,
    build_ellipse_parameter_controller,
    build_radial_random_feature_parameter_controller,
)
from sdf_inverse.optimization import (
    ComplexScatteredData,
    ParameterFDConfig,
    normalized_complex_residual,
    run_parameter_fd_inverse,
)
from run_sdf_inverse_comparison import (
    _build_initial_model,
    _inverse_config_for_controller,
    _prepare_output_directory,
)
from sdf_to_ordered_boundary import FrontendError


TARGET_CENTER = (0.5, 0.5)
TARGET_RADIUS = 0.05
INITIAL_CENTER = (0.49, 0.51)
INITIAL_RADIUS = 0.06


@pytest.fixture(scope="module")
def circle_case() -> SimpleNamespace:
    """Small non-degenerate paired experiment with an independent oracle."""

    angles = np.linspace(0.0, 2.0 * np.pi, 6, endpoint=False, dtype=np.float64)
    standoff = 0.30
    angular_separation = float(cfg.TX_RX_OFFSET) / standoff
    sources = np.column_stack(
        (
            TARGET_CENTER[0] + standoff * np.cos(angles),
            TARGET_CENTER[1] + standoff * np.sin(angles),
        )
    )
    receivers = np.column_stack(
        (
            TARGET_CENTER[0] + standoff * np.cos(angles + angular_separation),
            TARGET_CENTER[1] + standoff * np.sin(angles + angular_separation),
        )
    )
    angular_frequencies = 2.0 * np.pi * np.array([0.25e9, 0.50e9])
    exterior_spec = MaterialSpec(epsr=cfg.SAND_EPSR, sigma=cfg.SAND_SIGMA)
    interior_spec = MaterialSpec(epsr=cfg.PLASTIC_EPSR, sigma=cfg.PLASTIC_SIGMA)
    problem = PairedForwardProblem(
        source_points=sources,
        receiver_points=receivers,
        angular_frequencies=angular_frequencies,
        source_strengths=1.0 + 0.0j,
        exterior=exterior_spec,
        interior=interior_spec,
        eps0=cfg.EPS0,
        mu0=cfg.MU0,
    )
    exact_scattered = penetrable_cylinder_frequency_response(
        receivers,
        sources,
        angular_frequencies,
        1.0 + 0.0j,
        exterior=Material(epsr=cfg.SAND_EPSR, sigma=cfg.SAND_SIGMA),
        interior=Material(epsr=cfg.PLASTIC_EPSR, sigma=cfg.PLASTIC_SIGMA),
        eps0=cfg.EPS0,
        mu0=cfg.MU0,
        radius=TARGET_RADIUS,
        center=TARGET_CENTER,
        include_incident=False,
    )
    geometry_config = OrderedSDFGeometryConfig(
        bounds=((0.35, 0.35), (0.65, 0.65)),
        # This spacing avoids placing the circle's cardinal points exactly on
        # marching-squares vertices while retaining a cheap deterministic fit.
        grid_shape=(65, 65),
        projected_samples=32,
        bandwidth=4,
        num_nodes=32,
        arclength_dense_resolution=64,
        validation_resolution=64,
    )
    return SimpleNamespace(
        problem=problem,
        exact_scattered=exact_scattered,
        geometry_config=geometry_config,
    )


def test_circle_sdf_and_bounded_parameter_controller() -> None:
    model = CircleSDF2D(
        center=INITIAL_CENTER,
        radius=INITIAL_RADIUS,
        dtype=torch.float64,
    )
    points = torch.tensor(
        [INITIAL_CENTER, (INITIAL_CENTER[0] + INITIAL_RADIUS, INITIAL_CENTER[1])],
        dtype=torch.float64,
    )
    np.testing.assert_allclose(
        model(points).detach().cpu().numpy().reshape(-1),
        [-INITIAL_RADIUS, 0.0],
        atol=2.0e-15,
    )

    controller = build_circle_parameter_controller(
        model,
        center_bounds=((0.4, 0.6), (0.4, 0.6)),
        radius_bounds=(0.025, 0.09),
    )
    assert controller.names == ("center_x", "center_y", "log_radius")
    np.testing.assert_allclose(
        controller.parameter_vector(),
        [*INITIAL_CENTER, math.log(INITIAL_RADIUS)],
        atol=0.0,
        rtol=2.0e-15,
    )

    updated = np.array([0.51, 0.49, math.log(0.055)], dtype=np.float64)
    controller.assign(updated)
    np.testing.assert_allclose(controller.parameter_vector(), updated)
    assert controller.physical_parameter_dict() == pytest.approx(
        {"center_x": 0.51, "center_y": 0.49, "radius": 0.055}
    )
    projected = controller.project(np.array([0.8, 0.2, math.log(0.2)]))
    np.testing.assert_allclose(
        projected,
        [controller.upper_bounds[0], controller.lower_bounds[1], controller.upper_bounds[2]],
    )

    large_model = torch.nn.Linear(2, 16, dtype=torch.float64)
    with pytest.raises(ValueError, match="adjoint"):
        TorchParameterController(
            large_model,
            lower_bounds=-1.0,
            upper_bounds=1.0,
            max_parameters=32,
        )


def test_single_frequency_residual_is_not_erased() -> None:
    observed = np.array([[1.0 + 2.0j], [2.0 - 1.0j]])
    predicted = observed + np.array([[0.1 - 0.2j], [-0.3 + 0.4j]])

    residual, relative_l2 = normalized_complex_residual(predicted, observed)

    assert residual.shape == (4,)
    assert np.linalg.norm(residual) > 0.0
    assert relative_l2 == pytest.approx(
        np.linalg.norm(predicted - observed) / np.linalg.norm(observed)
    )


def test_grid_aligned_exact_zero_vertices_do_not_break_contour_extraction() -> None:
    """Exact grid zeros may repeat marching-squares vertices, but not geometry."""

    geometry = build_ordered_sdf_geometry(
        CircleSDF2D(center=TARGET_CENTER, radius=TARGET_RADIUS),
        OrderedSDFGeometryConfig(
            bounds=((0.35, 0.35), (0.65, 0.65)),
            # h=0.005 m and radius=10h: cardinal zero-set points are grid nodes.
            grid_shape=(61, 61),
            projected_samples=32,
            bandwidth=4,
            num_nodes=32,
            arclength_dense_resolution=64,
            validation_resolution=64,
        ),
    )

    assert geometry.curve.num_nodes == 32
    assert geometry.maximum_curve_sdf_residual < 1.0e-8


def test_artifact_directory_requires_explicit_overwrite(tmp_path) -> None:
    output = tmp_path / "inverse-run"
    output.mkdir()
    known_artifact = output / "metrics.json"
    unrelated_file = output / "keep-me.txt"
    known_artifact.write_text("stale", encoding="utf-8")
    unrelated_file.write_text("unrelated", encoding="utf-8")

    with pytest.raises(FileExistsError, match="--overwrite"):
        _prepare_output_directory(output, overwrite=False)

    _prepare_output_directory(output, overwrite=True)
    assert not known_artifact.exists()
    assert unrelated_file.read_text(encoding="utf-8") == "unrelated"


def test_common_ordered_geometry_reaches_both_forward_solvers_and_mie(
    circle_case: SimpleNamespace,
) -> None:
    model = CircleSDF2D(center=TARGET_CENTER, radius=TARGET_RADIUS)
    results = {
        solver: predict_paired_response(
            model,
            circle_case.problem,
            circle_case.geometry_config,
            solver=solver,
        )
        for solver in ("mod", "kress")
    }

    for result in results.values():
        assert result.scattered_response.shape == (6, 2)
        assert result.total_response.shape == (6, 2)
        assert np.all(np.isfinite(result.scattered_response))
        assert np.max(result.linear_system_relative_residuals) < 1.0e-12
        assert result.geometry_build.maximum_curve_sdf_residual < 1.0e-8

    # Both adapters must see exactly the same ordered nodes and arc weights.
    np.testing.assert_allclose(
        results["mod"].geometry_build.curve.points,
        results["kress"].geometry_build.curve.points,
        atol=2.0e-14,
        rtol=0.0,
    )
    np.testing.assert_allclose(
        results["mod"].geometry_build.curve.arc_length_weights,
        results["kress"].geometry_build.curve.arc_length_weights,
        atol=2.0e-14,
        rtol=0.0,
    )

    curve = results["kress"].geometry_build.curve
    mod_boundary = ordered_curve_to_mod_boundary(
        curve, circle_case.geometry_config.bounds
    )
    mod_points = mod_boundary.points.detach().cpu().numpy()
    mod_normals = mod_boundary.normals.detach().cpu().numpy()
    ordinary_weights = (
        mod_boundary.quadrature_weights.detach().cpu().numpy().reshape(-1)
    )
    strict_weights = (
        mod_boundary.strict_quadrature_weights.detach().cpu().numpy().reshape(-1)
    )
    np.testing.assert_allclose(mod_points, curve.points, atol=0.0, rtol=0.0)
    np.testing.assert_allclose(mod_normals, curve.normals, atol=0.0, rtol=0.0)
    np.testing.assert_allclose(
        ordinary_weights, curve.arc_length_weights, atol=0.0, rtol=0.0
    )
    np.testing.assert_allclose(
        strict_weights, curve.arc_length_weights, atol=0.0, rtol=0.0
    )
    assert not np.shares_memory(mod_points, curve.points)
    assert not np.shares_memory(mod_normals, curve.normals)
    assert mod_boundary.quadrature_weights.data_ptr() != (
        mod_boundary.strict_quadrature_weights.data_ptr()
    )

    errors = {
        solver: float(
            np.linalg.norm(result.scattered_response - circle_case.exact_scattered)
            / np.linalg.norm(circle_case.exact_scattered)
        )
        for solver, result in results.items()
    }
    assert errors["mod"] < 2.0e-2, errors
    assert errors["kress"] < 1.0e-6, errors
    assert errors["kress"] < 1.0e-3 * errors["mod"], errors


@pytest.mark.parametrize(
    ("solver", "maximum_final_relative_error"),
    (("mod", 1.0e-2), ("kress", 1.0e-4)),
)
def test_wrong_circle_recovers_with_monotone_fixed_objective(
    solver: str,
    maximum_final_relative_error: float,
    circle_case: SimpleNamespace,
) -> None:
    model = CircleSDF2D(
        center=INITIAL_CENTER,
        radius=INITIAL_RADIUS,
        dtype=torch.float64,
    )
    controller = build_circle_parameter_controller(
        model,
        center_bounds=((0.4, 0.6), (0.4, 0.6)),
        radius_bounds=(0.025, 0.09),
    )
    data = ComplexScatteredData(
        forward_problem=circle_case.problem,
        observed_scattered_response=circle_case.exact_scattered,
    )
    inverse = run_parameter_fd_inverse(
        model,
        controller,
        data,
        circle_case.geometry_config,
        solver=solver,
        config=ParameterFDConfig(
            max_iterations=5,
            finite_difference_steps=np.array([5.0e-5, 5.0e-5, 4.0e-4]),
            max_steps=np.array([1.0e-2, 1.0e-2, 1.0e-1]),
            initial_damping=1.0e-3,
            max_damping_trials=6,
            max_backtracks=8,
            gradient_tolerance=1.0e-9,
            loss_tolerance=1.0e-14,
            relative_step_tolerance=1.0e-9,
        ),
    )

    losses = np.array([iteration.loss for iteration in inverse.iterations])
    assert losses.size >= 4
    assert np.all(np.diff(losses) <= 32.0 * np.finfo(np.float64).eps)
    assert losses[0] / losses[-1] > 1.0e3
    assert inverse.final_iteration.relative_l2_error < maximum_final_relative_error
    assert max(
        iteration.maximum_system_residual for iteration in inverse.iterations
    ) < 1.0e-12
    assert inverse.maximum_system_residual < 1.0e-12

    physical = inverse.final_iteration.physical_parameters
    center_error = math.hypot(
        physical["center_x"] - TARGET_CENTER[0],
        physical["center_y"] - TARGET_CENTER[1],
    )
    radius_error = abs(physical["radius"] - TARGET_RADIUS)
    assert center_error < 5.0e-4
    assert radius_error < 5.0e-4
    np.testing.assert_allclose(
        controller.parameter_vector(), inverse.final_iteration.parameter_vector
    )


@pytest.fixture(scope="module")
def noncircle_geometry_config() -> OrderedSDFGeometryConfig:
    return OrderedSDFGeometryConfig(
        bounds=((0.30, 0.30), (0.70, 0.70)),
        grid_shape=(97, 97),
        projected_samples=64,
        bandwidth=10,
        num_nodes=64,
        arclength_dense_resolution=512,
        validation_resolution=256,
    )


@pytest.mark.parametrize("kind", ("ellipse", "random_features"))
def test_non_distance_initial_models_are_noncircular_regular_closed_fields(
    kind: str,
    noncircle_geometry_config: OrderedSDFGeometryConfig,
) -> None:
    model, controller = _build_initial_model(kind)
    geometry = build_ordered_sdf_geometry(model, noncircle_geometry_config)
    physical = controller.physical_parameter_dict()
    radii = np.linalg.norm(
        geometry.curve.points
        - np.array([physical["center_x"], physical["center_y"]])[None, :],
        axis=1,
    )
    assert np.ptp(radii) >= 2.0e-3
    assert geometry.maximum_normalized_curve_residual < 2.0e-4

    points = torch.tensor(
        geometry.curve.points,
        dtype=torch.float64,
        requires_grad=True,
    )
    values = model(points).reshape(-1)
    gradients = torch.autograd.grad(values.sum(), points)[0]
    maximum_unit_deviation = torch.max(
        torch.abs(torch.linalg.norm(gradients, dim=1) - 1.0)
    )
    assert float(maximum_unit_deviation) >= 5.0e-2
    assert getattr(model, "claims_signed_distance") is False


def test_non_distance_model_controllers_round_trip_and_random_features_repeat() -> None:
    ellipse = EllipseLevelSet2D(
        center=(0.48, 0.52),
        semi_axes=(0.072, 0.038),
        rotation_radians=0.4,
    )
    ellipse_controller = build_ellipse_parameter_controller(
        ellipse,
        center_bounds=((0.4, 0.6), (0.4, 0.6)),
        semi_axis_bounds=(0.025, 0.09),
    )
    ellipse_vector = ellipse_controller.parameter_vector()
    ellipse_controller.assign(ellipse_vector)
    np.testing.assert_array_equal(
        ellipse_controller.parameter_vector(), ellipse_vector
    )

    first = RadialRandomFeatureImplicit2D(random_seed=17, radius=0.06)
    second = RadialRandomFeatureImplicit2D(random_seed=17, radius=0.06)
    first_controller = build_radial_random_feature_parameter_controller(
        first,
        center_bounds=((-0.1, 0.1), (-0.1, 0.1)),
        radius_bounds=(0.025, 0.075),
    )
    assert first_controller.num_parameters == 7
    points = torch.tensor(
        [[0.06, 0.0], [0.0, 0.06], [-0.04, 0.03]], dtype=torch.float64
    )
    torch.testing.assert_close(first(points), second(points), rtol=0.0, atol=0.0)
    torch.testing.assert_close(
        first.hidden_weights, second.hidden_weights, rtol=0.0, atol=0.0
    )


def test_unconstrained_random_mlp_fails_before_forward_solve(
    noncircle_geometry_config: OrderedSDFGeometryConfig,
) -> None:
    torch.manual_seed(0)
    model = torch.nn.Sequential(
        torch.nn.Linear(2, 4, dtype=torch.float64),
        torch.nn.Tanh(),
        torch.nn.Linear(4, 1, dtype=torch.float64),
    )
    with pytest.raises(FrontendError):
        build_ordered_sdf_geometry(model, noncircle_geometry_config)


@pytest.mark.parametrize("kind", ("ellipse", "random_features"))
@pytest.mark.parametrize("solver", ("mod", "kress"))
def test_noncircle_initializations_reduce_the_same_mie_objective(
    kind: str,
    solver: str,
    circle_case: SimpleNamespace,
    noncircle_geometry_config: OrderedSDFGeometryConfig,
) -> None:
    model, controller = _build_initial_model(kind)
    inverse = run_parameter_fd_inverse(
        model,
        controller,
        ComplexScatteredData(circle_case.problem, circle_case.exact_scattered),
        noncircle_geometry_config,
        solver=solver,
        config=_inverse_config_for_controller(controller, max_iterations=2),
    )
    losses = np.asarray([record.loss for record in inverse.iterations])
    assert losses.size == 3
    assert np.all(np.diff(losses) < 0.0)
    assert losses[-1] < 0.5 * losses[0]
    assert inverse.maximum_system_residual < 1.0e-10
