"""Solver-neutral inverse tools for smooth single-component Torch implicits.

The public seam deliberately separates implicit geometry, forward prediction,
and low-dimensional numerical optimization.  Both MOD and Kress therefore see
the same ordered boundary and the same inverse objective.
"""

from .forward import (
    IndexedForwardProblem,
    IndexedForwardResult,
    MaterialSpec,
    PairedForwardProblem,
    PairedForwardResult,
    predict_paired_curve_response,
    predict_paired_response,
    predict_indexed_curve_response,
    predict_indexed_response,
)
from .curve_updates import (
    DirectNormalModeCurveUpdate,
    DirectRadialFourierCurveUpdate,
    RadialFourierCurveState,
    apply_normal_mode_update,
    apply_radial_fourier_update,
    fit_radial_fourier_curve_state,
    radial_fourier_displacement_basis,
    radial_fourier_parameterization,
    radial_fourier_state_curve,
    smooth_normal_mode_values,
)
from .geometry import (
    OrderedSDFGeometryBuild,
    OrderedSDFGeometryConfig,
    OrderedSDFGeometryError,
    build_ordered_sdf_geometry,
    ordered_curve_to_mod_boundary,
)
from .neural import (
    NeuralRedistanceConfig,
    NeuralRedistanceResult,
    SmoothMLPSDF2D,
    redistance_neural_sdf_to_curve,
    signed_distance_to_curve_polygon,
)
from .neural_optimization import (
    AlternatingNeuralInverseConfig,
    AlternatingNeuralInverseResult,
    NeuralInverseIteration,
    NeuralSDFExportResult,
    SmoothNormalModeUpdate2D,
    maximum_curve_set_distance,
    export_neural_sdf_representation,
    normal_mode_count,
    radial_spectral_tail_rms,
    resolvable_maximum_mode,
    run_alternating_neural_inverse,
)
from .models import (
    CircleSDF2D,
    EllipseLevelSet2D,
    PretrainingReport,
    RadialRandomFeatureImplicit2D,
    SirenImplicitField2D,
    StarLevelSet2D,
    TorchParameterController,
    build_circle_parameter_controller,
    build_ellipse_parameter_controller,
    build_radial_random_feature_parameter_controller,
    build_siren_parameter_controller,
    build_star_parameter_controller,
    circle_parameter_controller,
    first_order_distance_supervisor,
    pretrain_implicit_field,
)
from .nystrom_oracle import (
    NystromObservations,
    nystrom_paired_response,
    nystrom_self_convergence,
)
from .optimization import (
    ComplexScatteredData,
    ParameterFDConfig,
    ParameterFDInverseResult,
    ParameterFDIteration,
    normalized_complex_residual,
    run_parameter_fd_inverse,
)
from .implicit_adjoint import (
    ImplicitMLPAdjointConfig,
    ImplicitMLPIteration,
    ImplicitMLPInverseResult,
    implicit_mlp_data_gradient,
    run_implicit_mlp_adjoint_inverse,
)
from .targets import StarShape
from .continuous_distance import (
    ContinuousDistanceRefinementError,
    signed_distance_to_continuous_curve,
)
from .radial_topology import (
    BirthResult,
    BirthTrial,
    MultiRadialFDIteration,
    MultiRadialFDResult,
    MultiRadialFourierState,
    MultiRadialObjectiveEvaluation,
    TDRasterResult,
    TopologicalDerivativeResult,
    build_td_raster,
    circle_radial_fourier_state,
    evaluate_birth_ladder,
    evaluate_current_domain_topological_derivative,
    evaluate_multiradial_objective,
    iteration01_optimizer_config,
    iteration01_solve_config,
    run_multiradial_fd_inverse,
)
from .explicit_fourier import CartesianFourierCurveState
from .topology_controller import (
    TopologyControllerConfig,
    TopologyInverseResult,
    build_topology_workspace,
    run_topology_aware_fourier_inverse,
)

__all__ = [
    "CartesianFourierCurveState",
    "TopologyControllerConfig",
    "TopologyInverseResult",
    "build_topology_workspace",
    "run_topology_aware_fourier_inverse",
    "ImplicitMLPAdjointConfig",
    "ImplicitMLPIteration",
    "ImplicitMLPInverseResult",
    "implicit_mlp_data_gradient",
    "run_implicit_mlp_adjoint_inverse",
    "AlternatingNeuralInverseConfig",
    "AlternatingNeuralInverseResult",
    "BirthResult",
    "BirthTrial",
    "CircleSDF2D",
    "ComplexScatteredData",
    "ContinuousDistanceRefinementError",
    "DirectNormalModeCurveUpdate",
    "DirectRadialFourierCurveUpdate",
    "EllipseLevelSet2D",
    "MaterialSpec",
    "MultiRadialFDIteration",
    "MultiRadialFDResult",
    "MultiRadialFourierState",
    "MultiRadialObjectiveEvaluation",
    "NystromObservations",
    "NeuralInverseIteration",
    "NeuralSDFExportResult",
    "NeuralRedistanceConfig",
    "NeuralRedistanceResult",
    "OrderedSDFGeometryBuild",
    "OrderedSDFGeometryConfig",
    "OrderedSDFGeometryError",
    "PairedForwardProblem",
    "PairedForwardResult",
    "IndexedForwardProblem",
    "IndexedForwardResult",
    "predict_indexed_curve_response",
    "predict_indexed_response",
    "ParameterFDConfig",
    "ParameterFDInverseResult",
    "ParameterFDIteration",
    "PretrainingReport",
    "RadialRandomFeatureImplicit2D",
    "RadialFourierCurveState",
    "SirenImplicitField2D",
    "StarLevelSet2D",
    "StarShape",
    "SmoothMLPSDF2D",
    "SmoothNormalModeUpdate2D",
    "TorchParameterController",
    "TDRasterResult",
    "TopologicalDerivativeResult",
    "apply_normal_mode_update",
    "apply_radial_fourier_update",
    "build_circle_parameter_controller",
    "build_td_raster",
    "build_ellipse_parameter_controller",
    "build_ordered_sdf_geometry",
    "build_radial_random_feature_parameter_controller",
    "build_siren_parameter_controller",
    "build_star_parameter_controller",
    "circle_parameter_controller",
    "circle_radial_fourier_state",
    "evaluate_birth_ladder",
    "evaluate_current_domain_topological_derivative",
    "evaluate_multiradial_objective",
    "first_order_distance_supervisor",
    "fit_radial_fourier_curve_state",
    "maximum_curve_set_distance",
    "export_neural_sdf_representation",
    "normalized_complex_residual",
    "nystrom_paired_response",
    "nystrom_self_convergence",
    "normal_mode_count",
    "iteration01_optimizer_config",
    "iteration01_solve_config",
    "radial_spectral_tail_rms",
    "radial_fourier_displacement_basis",
    "radial_fourier_parameterization",
    "signed_distance_to_continuous_curve",
    "radial_fourier_state_curve",
    "resolvable_maximum_mode",
    "ordered_curve_to_mod_boundary",
    "predict_paired_curve_response",
    "predict_paired_response",
    "pretrain_implicit_field",
    "redistance_neural_sdf_to_curve",
    "run_alternating_neural_inverse",
    "run_multiradial_fd_inverse",
    "run_parameter_fd_inverse",
    "signed_distance_to_curve_polygon",
    "smooth_normal_mode_values",
]
